[package]
name = "promql"
version = "0.1.0"
authors = ["detailyang <detailyang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
humantime = "2.1.0"
thiserror = "1.0"
log = "0.4"